export interface Track {
  id: string;
  user_id: string;
  title: string;
  prompt: string;
  improved_prompt?: string | null;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  audio_url?: string | null;
  cover_url?: string | null;
  video_url?: string | null;
  suno_id?: string | null;
  model_name?: string | null;
  lyrics?: string | null;
  style_tags?: string[] | null;
  genre?: string | null;
  mood?: string | null;
  is_public?: boolean | null;
  view_count?: number | null;
  like_count?: number | null;
  play_count?: number | null;
  download_count?: number | null;
  created_at: string;
  updated_at: string;
  duration_seconds?: number | null;
  has_stems?: boolean | null;
  has_vocals?: boolean | null;
  provider: string | null;
  metadata?: Record<string, any> | null;
  parentTrackId?: string;
  versionNumber?: number;
  isMasterVersion?: boolean;
  sourceVersionNumber?: number | null;
  suno_task_id?: string;
  mureka_task_id?: string;
  selectedVersionId?: string;
  versions?: any[];
}
