-- Migration: Add 'draft' status to track status system
-- Date: 2025-11-05
-- Purpose: Implement draft status for tracks with lyrics but not yet in generation

-- Step 1: Create enum type for track status
CREATE TYPE track_status AS ENUM (
  'pending',    -- Track created, awaiting lyrics or generation
  'draft',      -- Track has lyrics, ready for generation
  'processing', -- Currently being generated by AI provider
  'completed',  -- Generation completed successfully
  'failed'      -- Generation failed with error
);

-- Step 2: Add new column with enum type
ALTER TABLE tracks
  ADD COLUMN status_new track_status;

-- Step 3: Migrate existing data
-- Map TEXT status to enum status
UPDATE tracks
SET status_new = CASE
  WHEN status = 'pending' THEN 'pending'::track_status
  WHEN status = 'processing' THEN 'processing'::track_status
  WHEN status = 'completed' THEN 'completed'::track_status
  WHEN status = 'failed' THEN 'failed'::track_status
  ELSE 'pending'::track_status  -- Default for unknown statuses
END;

-- Step 4: Make status_new NOT NULL (all rows should have value now)
ALTER TABLE tracks
  ALTER COLUMN status_new SET NOT NULL;

-- Step 5: Drop old column and rename new column
ALTER TABLE tracks
  DROP COLUMN status;

ALTER TABLE tracks
  RENAME COLUMN status_new TO status;

-- Step 6: Set default value
ALTER TABLE tracks
  ALTER COLUMN status SET DEFAULT 'pending'::track_status;

-- Step 7: Create index for better performance
CREATE INDEX IF NOT EXISTS idx_tracks_status ON tracks(status);

-- Step 8: Add comment for documentation
COMMENT ON COLUMN tracks.status IS 'Track generation status: pending (awaiting), draft (has lyrics), processing (generating), completed (success), failed (error)';

-- Step 9: Create helper function to check if track can be generated
CREATE OR REPLACE FUNCTION can_generate_track(track_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  track_status track_status;
BEGIN
  SELECT status INTO track_status
  FROM tracks
  WHERE id = track_id;

  -- Track can be generated if it's in pending or draft status
  RETURN track_status IN ('pending', 'draft');
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION can_generate_track(UUID) IS 'Returns true if track is in a state where it can be generated (pending or draft)';

-- Step 10: Create trigger to auto-set draft status when lyrics added
CREATE OR REPLACE FUNCTION auto_set_draft_status()
RETURNS TRIGGER AS $$
BEGIN
  -- If lyrics are being added to a pending track, change status to draft
  IF NEW.lyrics IS NOT NULL AND NEW.lyrics != ''
     AND OLD.lyrics IS NULL OR OLD.lyrics = ''
     AND NEW.status = 'pending'::track_status THEN
    NEW.status := 'draft'::track_status;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_auto_draft_status
  BEFORE UPDATE ON tracks
  FOR EACH ROW
  EXECUTE FUNCTION auto_set_draft_status();

COMMENT ON TRIGGER trigger_auto_draft_status ON tracks IS 'Automatically set status to draft when lyrics are added to pending track';

-- Rollback script (for reference, commented out):
-- DROP TRIGGER IF EXISTS trigger_auto_draft_status ON tracks;
-- DROP FUNCTION IF EXISTS auto_set_draft_status();
-- DROP FUNCTION IF EXISTS can_generate_track(UUID);
-- DROP INDEX IF EXISTS idx_tracks_status;
-- ALTER TABLE tracks ALTER COLUMN status TYPE TEXT;
-- DROP TYPE IF EXISTS track_status;
